services:
  blog_dashboard:
    container_name: blog_dashboard
    image: image_blog_dashboard
    build: .
    ports:
      - "8081:80"
    networks:
      - my_network

  caddy:
    image: caddy:latest
    container_name: blog_dashboard_reverse_proxy
    restart: unless-stopped
    ports:
      - "8090:80"
      - "444:443"
    volumes:
      - ./Caddyfile:/etc/caddy/Caddyfile
      - caddy_data:/data
      - caddy_config:/config
    networks:
      - my_network
    depends_on:
      - blog_dashboard

networks:
  my_network:
    external: true

volumes:
  caddy_data:
  caddy_config:
