services:
  blog_dashboard:
    container_name: blog_dashboard
    build: .
    restart: always
    networks:
      - my_network
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - ./Caddyfile:/etc/caddy/Caddyfile:ro

networks:
  my_network:
    driver: bridge
