name: Deploy React.js Frontend

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Connect to VPS and Clone if Needed
        uses: appleboy/ssh-action@v0.1.10
        with:
          host: ${{ secrets.VPS_HOST }}
          username: ${{ secrets.VPS_USERNAME }}
          key: ${{ secrets.VPS_SSH_KEY }}
          script: |
            PROJECT_PATH="/var/www/docker/blog_dashboard"

            if [ -d "$PROJECT_PATH/.git" ]; then
              echo "Repository exists, skipping clone."
            else
              echo "Repository does not exist or is broken. Cloning..."
              rm -rf $PROJECT_PATH  # Remove any broken directory
              git clone https://github.com/Ahmadfaisalkeren/blog_dashboard.git $PROJECT_PATH
            fi

      - name: Pull Latest Changes
        uses: appleboy/ssh-action@v0.1.10
        with:
          host: ${{ secrets.VPS_HOST }}
          username: ${{ secrets.VPS_USERNAME }}
          key: ${{ secrets.VPS_SSH_KEY }}
          script: |
            cd /var/www/docker/blog_dashboard
            git reset --hard  # Ensure clean working directory
            git pull origin main

      - name: Build and Restart Docker Services
        uses: appleboy/ssh-action@v0.1.10
        with:
          host: ${{ secrets.VPS_HOST }}
          username: ${{ secrets.VPS_USERNAME }}
          key: ${{ secrets.VPS_SSH_KEY }}
          script: |
            cd /var/www/docker/blog_dashboard
            docker compose up -d --build
